// frontend/react/src/App.tsx
import { useState, useEffect } from 'react'
import Navbar from './components/Navbar';
import styles from './App.module.css'
import Chat from './components/Chat';
import type { Message } from './types';

function App() {
  const [ws, setWs] = useState<WebSocket | undefined>(undefined);
  const [rooms, setRooms] = useState<string[]>([]);
  const [selectedRoom, setSelectedRoom] = useState<string | undefined>(undefined);
  const [messages, setMessages] = useState<Message[]>([]);

  useEffect(() => {
    const websocket = new WebSocket('ws://localhost:8080');

    websocket.onmessage = (message) => {
      const data = JSON.parse(message.data);
      if (data.action === 'listed') {
        setRooms(data.chatrooms);
      } else if (data.action === 'message') {
        setMessages((messages) => [data.content, ...messages]);
      }
    };

    setWs(websocket);

    return () => {
      websocket.close();
    };

  }, []);

  useEffect(() => {
    if (selectedRoom) {
      ws?.send(JSON.stringify({
        action: 'join',
        chatroomId: selectedRoom,
      }));
    }
  }, [selectedRoom, ws]);

  function listRooms() {
    ws?.send(JSON.stringify({
      action: 'list',
    }));
  }

  function createRoom() {
    ws?.send(JSON.stringify({
      action: 'create',
    }));
  }

  function sendMessage(message: string, user: string) {
    ws?.send(JSON.stringify({
      action: 'message',
      chatroomId: selectedRoom,
      content: {
        user,
        message,
      }
    }));
  }

  return (
    <main className={styles.main}>
      <Navbar roomList={rooms} listRooms={listRooms} createRoom={createRoom} selectRoom={setSelectedRoom} />
      <Chat selectedRoom={selectedRoom} messages={messages} sendMessage={sendMessage} />
    </main>
  )
}

export default App

// frontend/vue/src/App.vue
<script setup lang="ts">
import { reactive } from "vue";
import Navbar from "./components/Navbar.vue";
import Chat from "./components/Chat.vue";

import type { Message } from "./types/message";

const state = reactive({
  roomList: [] as string[],
  messages: [] as Message[],
  selectedRoom: "",
});

const socket = new WebSocket("ws://localhost:8080/ws");

socket.onmessage = (event) => {
  const data = JSON.parse(event.data);
  if (data.action === "listed") {
    state.roomList = data.chatrooms;
  } else if (data.action === "message") {
    state.messages = [data.content, ...state.messages];
  }
};

function listRooms() {
  socket?.send(
    JSON.stringify({
      action: "list",
    })
  );
}

function createRoom() {
  socket?.send(
    JSON.stringify({
      action: "create",
    })
  );
}

function sendMessage(message: string, user: string) {
  socket?.send(
    JSON.stringify({
      action: "message",
      chatroomId: state.selectedRoom,
      content: {
        user,
        message,
      },
    })
  );
}

function selectRoom(room: string) {
  state.selectedRoom = room;
  socket?.send(
    JSON.stringify({
      action: "join",
      chatroomId: room,
    })
  );
}
</script>

<template>
  <Navbar
    :roomList="state.roomList"
    :listRooms="listRooms"
    :createRoom="createRoom"
    :joinRoom="selectRoom"
  />
  <Chat
    :selectedRoom="state.selectedRoom"
    :messages="state.messages"
    :sendMessage="sendMessage"
  />
</template>

<style scoped></style>
