// frontend/vue/src/components/Navbar.vue
<script setup lang="ts">
import { ref, reactive, onMounted, onBeforeUnmount } from "vue";

const props = defineProps<{
  roomList: string[];
  createRoom: () => void;
  joinRoom: (room: string) => void;
  listRooms: () => void;
}>();

const state = reactive({
  showRoomList: false,
});

const dropdownRef = ref<HTMLDivElement | null>(null);
const buttonRef = ref<HTMLButtonElement | null>(null);

onMounted(() => {
  document.addEventListener("mousedown", handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleClickOutside);
});

function handleClickOutside(event: MouseEvent) {
  if (
    dropdownRef.value && !dropdownRef.value.contains(event.target as Node) &&
    buttonRef.value && !buttonRef.value.contains(event.target as Node)
  ) {
    state.showRoomList = false;
  }
}

function openRoomList() {
  if (state.showRoomList) {
    state.showRoomList = false;
  } else {
    props.listRooms();
    state.showRoomList = true;
  }
}

function handleSelectRoom(room: string) {
  props.joinRoom(room);
  state.showRoomList = false;
}
</script>

<template>
  <nav class="navbar">
    <button class="dropdownButton" @click="openRoomList" ref="buttonRef">
      Rooms
      {{ state.showRoomList ? "▲" : "▼" }}
    </button>
    <button @click="createRoom">Create Room</button>
    <div v-if="state.showRoomList" class="dropdown" ref="dropdownRef">
      <div v-for="(room, index) in roomList" :key="index" class="room">
        {{ room }}
        <button @click="handleSelectRoom(room)" class="joinButton">Join</button>
      </div>
      <p v-if="roomList.length === 0">No rooms available</p>
    </div>
  </nav>
</template>

<style scoped>
.navbar {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 10;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #1a1a1a;
}

.dropdownButton {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: row;
  gap: 10px;
}

.dropdown {
  position: absolute;
  top: 64px;
  left: 10px;
  z-index: 10;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #1a1a1a;
  border-radius: 8px;
  border: 1px solid #646cff;
  padding: 10px;
}

.hr {
  width: 100%;
  height: 1px;
  background-color: white;
  margin: 10px 0;
  border: none;
}

.joinButton {
  border-color: #64ff67;
  color: #64ff67;
}
.joinButton:hover {
  color: white;
  border-color: white;
}
</style>

// frontend/svelte/src/lib/Navbar.svelte
<script lang="ts">
  import { onMount } from "svelte";

  export let rooms: string[] = [];
  export let listRooms: () => void;
  export let createRoom: () => void;
  export let joinRoom: (room: string) => void;

  let showDropdown = false;
  let dropdown: HTMLDivElement;
  let dropdownButton: HTMLButtonElement;

  onMount(() => {
    const handleClickOutside = (event: any) => {
      if (
        dropdown &&
        !dropdown.contains(event.target) &&
        showDropdown &&
        event.target !== dropdownButton
      ) {
        showDropdown = false;
      }
    };

    window.addEventListener("click", handleClickOutside);

    return () => {
      window.removeEventListener("click", handleClickOutside);
    };
  });
</script>

<nav class="navbar">
  {#if showDropdown}
    <div class="dropdown" bind:this={dropdown}>
      {#each rooms as room}
        <div class="dropdown-content">
          {room}
          <button
            class="join-button"
            on:click={() => {
              joinRoom(room);
              showDropdown = false;
            }}
          >
            Join
          </button>
        </div>
        {#if room !== rooms[rooms.length - 1]}
          <hr />
        {/if}
      {/each}
    </div>
  {/if}
  <button
    bind:this={dropdownButton}
    on:click={() => {
      listRooms();
      showDropdown = !showDropdown;
    }}
  >
    Rooms
  </button>
  <button on:click={createRoom}>Create Room</button>
</nav>

<style>
  .navbar {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    display: flex;
    justify-content: space-between;
    padding-top: 1em;
    padding-bottom: 1em;
    background-color: #2b2b2b;
  }

  .join-button {
    margin-right: 0;
  }

  .dropdown {
    position: absolute;
    top: 82px;
    left: 1em;
    padding: 1em;
    border: 1px solid #646cff;
    border-radius: 0.5em;
    background-color: #2b2b2b;
  }

  .dropdown-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
  }
</style>
